FROM python:3.10-slim

WORKDIR /app

COPY ./backend /app/backend
COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["celery", "-A", "backend.tasks.celery_app", "worker", "--loglevel=info"]
